### ISSUE TITLE
Error parsing failure

### ISSUE THREAD

**Issue by pjechris** [aws-amplify/aws-appsync-realtime-client-ios#38]
When receiving a "unauthorized" error from server, websocket fail to parse it correctly.

Message from server:
```json
{
  "payload":{
    "errors":[{
      "errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException",
      "message":"Valid authorization header not provided.","errorCode":400
      }]
    },
   "type":"connection_error"
}
```

Socket result:
```
Swift.DecodingError.dataCorrupted(
    Swift.DecodingError.Context(
        codingPath: [CodingKeys(stringValue: "type", intValue: nil)],
        debugDescription: "Cannot initialize RealtimeConnectionProviderResponseType from invalid String value connection_error",
        underlyingError: nil
    )
)
```

**Comment by hasan-sf** [comment]
@pjechris We had similar issue.
After investigation, we figured out that the corresponding `AWS AppSync API key` was expired.
Updating the expiry date resolved the issue for us.

**Comment by lawmicha** [comment]
Thanks for bring this to our attention. I've started a draft PR in https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/69 to add the extra `connection_error` case to allow decoding. I'm currently thinking about ways to either return the auth error in an existing error case so that there is no API breaking changes or if we need another error case to encapsulate the auth error and message/code.

**Comment by pjechris** [comment]
I think this one can be closed? I don't see the error anymore in the last version.
